name: Sync assets on CDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install rclone
        run: sudo apt-get install -y rclone

      - name: sync to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET }}

          RCLONE_CONFIG_TARGET_TYPE: s3
          RCLONE_CONFIG_TARGET_PROVIDER: AWS
          RCLONE_CONFIG_TARGET_ENV_AUTH: true
          RCLONE_CONFIG_TARGET_ACL: public-read
        run: |
          rclone sync build/ target:$BUCKET_NAME --checksum --delete --fast-list --verbose
