name: Lint YAML
on:
  pull_request:
    branches:
      - main

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: "Lint YAML"
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # tag=v3
        with:
          file_or_dir: build
          strict: true
          config_file: .yamllint.yml